-- Создаем таблицу users
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_name TEXT NOT NULL UNIQUE, -- Имя пользователя должно быть уникальным
                       email TEXT NOT NULL UNIQUE, -- Email также должен быть уникальным
                       password_hash TEXT NOT NULL, -- Поле для хеша пароля не должно быть пустым
                       refresh_token TEXT, -- Поле для refresh токена (может быть NULL)
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Время создания записи
);

-- Создаем таблицу all_notes
CREATE TABLE all_notes (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           note TEXT NOT NULL, -- Поле заметки обязательно для заполнения
                           completed BOOLEAN DEFAULT FALSE, -- По умолчанию задача не выполнена
                           user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- Связь с таблицей users, при удалении пользователя удаляются его заметки
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Время создания записи
);
